DROP TABLE MedicalIssue cascade;
DROP TABLE Patient cascade;
DROP TABLE Drug cascade;
DROP TABLE DrugsTaken;
DROP TABLE Team cascade;
DROP TABLE Queue;
DROP TABLE EmergencyRoom;
DROP TABLE Treats;
DROP TABLE Treatments cascade;
DROP TABLE Procedure;